server:
  port: 5555

spring:
  application:
    name: gateway-server
    loadbalancer:
      ribbon:
        enabled: false
  cloud:
    discovery:
      enabled: true
    gateway:
      gdefault-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      metrics:
        enabled: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-app
          uri: lb://auth-app
          predicates:
            - Path=/api/*/auth/**
        - id: market-app
          uri: lb://market-app
          predicates:
            - Path=/api/*/market/**
#          filters:
#            - StripPrefix=1


eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
