server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/grizlen/SimlpeCRM
          default-label: master
          #          username: user
          #          password: 123123
          clone-on-start: true
          search-paths: config